# Generated by Django 4.2 on 2025-12-07 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(choices=[(7, '7 jours'), (30, '30 jours'), (90, '90 jours')], default=7)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='montant_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('commentaire', 'Commentaire'), ('telechargement', 'Téléchargement'), ('video_view', 'Visionnage vidéo'), ('daily_bonus', 'Bonus journalier'), ('achat_pub', 'Achat publicité'), ('partage', 'Partage'), ('rewarded_ad', 'Rewarded Ad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiementorangemoney',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paiementorangemoney',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué')], default='en_attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='VIP',
        ),
    ]
